language: node_js
node_js:
  - "10" # ends April 2021

sudo: required

script:
  - yarn install
  - yarn ci
  - yarn build
    
deploy:
  provider: pages
  local_dir: build
  fqdn: neopepes.com
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
